version: '2'
services:
  PostgreSQL03:
    image: postgres:latest
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${DOCKER_USER}'
      POSTGRES_PASSWORD: '${DOCKER_PASSWORD}'
  dockerTest:
    image: redis:latest
    restart: always
    ports:
      - '6378:6379'
